replicaCount: 1

image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent

postgres:
  database: coffee_db
  username: admin
  password: admin123

service:
  port: 5432

storage:
  size: 5Gi
  storageClass: standard
