apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service

          image: "mousama/notification-service:latest"

          ports:
          - name: http
            containerPort: 8855


          env:
          
            - name: RABBITMQ_HOST
              value: rabbitmq

            - name: RABBITMQ_USER
              valueFrom:
                  secretKeyRef:
                    name: rabbitmq-secret
                    key:  username

            - name: RABBITMQ_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: rabbitmq-secret
                    key: password

            - name: ORDER_NOTIFICATION_QUEUE
              value: order.notification.queue

            - name: USER_SERVICE_BASE_URL
              value: http://127.0.0.1:8000
              
            - name: POSTGRES_DB
              value: notification-db

            - name: DB_SERVICE
              value: postgres

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
