apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: notification-service
spec:
  hosts:
    - "coffee-shop.local"
  gateways:
    - coffee-shop-gateway
  http:
    - route:
        - destination:
            host: notification-service
            port:
              number: 8855
