apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: redis

spec:
  serviceName: redis

  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:

    metadata:
      labels:
        app: redis

    spec:

      containers:
       
      - name: redis
        
        image: "redis:7"


        ports:
        - containerPort: 6379

        volumeMounts:
        - name: redis-storage
          mountPath: /data

        command:
        - redis-server
        - "--appendonly"
        - "yes"

        env:
        - name: REDIS_HOST
          value: "redis"

        - name: REDIS_PORT
          value: "6379"

        - name: REDIS_DB
          value: "0"

        - name: REDIS_PASSWORD
          value: "password"
          
      volumes:
      - name: redis-storage

        persistentVolumeClaim:
          claimName: redis-data
